repos:
  - repo: local
    hooks:
      - id: rust-linting
        name: Rust linting
        entry: cargo fmt --all
        language: system
        pass_filenames: false

#      - id: rust-clippy
#        name: Rust clippy
#        entry: bash -c "cd ziggurat && cargo clippy --all-targets --all-features -- -Dclippy::all"
#        pass_filenames: false
#        types: [file, rust]
#        language: system
#        files: ^ziggurat/