/*
 * Ziggurat embedded-in-OpenThread-RCP C API (libziggurat_ot.a).
 *
 * Generated by cbindgen from src/lib.rs and src/platform.rs.
 */

#ifndef ZIGGURAT_H_
#define ZIGGURAT_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 `ziggurat_radio_tx_done` status values.
 */
enum ziggurat_tx_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  ZIGGURAT_TX_STATUS_ACKED = 0,
  ZIGGURAT_TX_STATUS_NO_ACK = 1,
  ZIGGURAT_TX_STATUS_CHANNEL_ACCESS_FAILURE = 2,
  ZIGGURAT_TX_STATUS_ABORTED = 3,
  ZIGGURAT_TX_STATUS_FAILED = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ziggurat_tx_status ziggurat_tx_status;
#else
typedef uint8_t ziggurat_tx_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 Radio programming, mirrored from `ziggurat_phy::RadioConfig` plus the derived
 PAN-coordinator flag. Extended address in little-endian (OT/over-the-air) byte
 order.
 */
typedef struct ziggurat_radio_config_t {
  uint8_t channel;
  int8_t tx_power_dbm;
  uint16_t short_address;
  uint16_t pan_id;
  uint8_t extended_address[8];
  bool promiscuous;
  bool rx_on_when_idle;
} ziggurat_radio_config_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Initialize and start the embedded stack. Called once, after OpenThread's instance
 and the NCP exist — there is no stop; switching the firmware back to plain-RCP use
 is an MCU reset. Idle until the first host frame arrives.
 */
void ziggurat_start(void);

/*
 Poll the executor. Call from the superloop whenever `ziggurat_platform_wake` was
 requested (extra calls are harmless).
 */
void ziggurat_process(void);

/*
 One inbound control-protocol frame from the host tunnel.
 */
void ziggurat_host_frame(const uint8_t *data,
                         size_t len);

/*
 NCP buffer space became available (VendorHandleFrameRemovedFromNcpBuffer).
 */
void ziggurat_host_send_ready(void);

/*
 The one-shot timer armed via `ziggurat_platform_timer_arm` fired.
 */
void ziggurat_timer_fired(void);

/*
 A frame was received on Ziggurat's instance (PSDU without FCS).
 */
void ziggurat_radio_rx(const uint8_t *psdu,
                       size_t len,
                       uint8_t channel,
                       int8_t rssi,
                       uint8_t lqi,
                       uint64_t timestamp_us);

/*
 The in-flight transmit finished.
 */
void ziggurat_radio_tx_done(ziggurat_tx_status status);

/*
 The energy scan finished with this peak RSSI.
 */
void ziggurat_radio_energy_scan_done(int8_t max_rssi_dbm);

/*
 Monotonic microseconds (otPlatTimeGet).
 */
extern uint64_t ziggurat_platform_time_now_us(void);

/*
 Arm the one-shot timer for an absolute deadline in the time_now_us domain;
 UINT64_MAX cancels. Expiry must call `ziggurat_timer_fired`.
 */
extern void ziggurat_platform_timer_arm(uint64_t deadline_us);

/*
 Request a `ziggurat_process` call from the main loop soon
 (otSysEventSignalPending). Must be safe to call from within any
 `ziggurat_*` call.
 */
extern void ziggurat_platform_wake(void);

/*
 Fill `buf` with `len` random bytes (otPlatEntropyGet).
 */
extern void ziggurat_platform_entropy(uint8_t *buf,
                                      size_t len);

/*
 AES-128 ECB one-block encrypt of the 16-byte `block` with the 16-byte
 `key`, in place.
 */
extern void ziggurat_platform_aes128_encrypt_block(const uint8_t *key,
                                                   uint8_t *block);

/*
 CCM* with a 16-byte `key` and a 13-byte `nonce` (sli_ccm_zigbee on EFR32).
 Encrypt: read `len` plaintext bytes from `input`, write ciphertext to
 `output` and the MIC to `tag`. Decrypt: the reverse, verifying `tag`;
 return nonzero on mismatch. `input`/`output` may alias.
 */
extern int32_t ziggurat_platform_ccm_crypt(bool encrypt,
                                           const uint8_t *key,
                                           const uint8_t *nonce,
                                           const uint8_t *auth,
                                           size_t auth_len,
                                           const uint8_t *input,
                                           uint8_t *output,
                                           size_t len,
                                           uint8_t *tag,
                                           size_t tag_len);

/*
 Queue one control-protocol frame to the host (unsolicited PROP_VALUE_IS on
 the ziggurat stream property). Return false when the NCP buffer is full;
 call `ziggurat_host_send_ready` once space frees up.
 */
extern bool ziggurat_platform_host_send(const uint8_t *data,
                                        size_t len);

/*
 Program the radio for ziggurat's interface (otLinkRaw*). Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_configure(const struct ziggurat_radio_config_t *config);

/*
 Change the receive channel. Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_set_channel(uint8_t channel);

/*
 Enable or disable promiscuous reception. Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_set_promiscuous(bool promiscuous);

/*
 Clear the source-address match table (frame-pending for sleepy children).
 */
extern void ziggurat_platform_radio_src_match_clear(void);

/*
 Add a short address to the source-address match table. Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_src_match_add_short(uint16_t address);

/*
 Add an 8-byte extended address (little-endian) to the source-address match
 table. Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_src_match_add_ext(const uint8_t *address);

/*
 Submit one frame; `psdu` excludes the FCS (account for it in mLength).
 Completion must call `ziggurat_radio_tx_done`. One in flight at a time.
 Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_transmit(const uint8_t *psdu,
                                                size_t len,
                                                uint8_t channel,
                                                bool csma_ca,
                                                uint8_t max_frame_retries,
                                                uint8_t max_csma_backoffs);

/*
 Start an energy scan; completion must call
 `ziggurat_radio_energy_scan_done`. Nonzero = failure.
 */
extern int32_t ziggurat_platform_radio_energy_scan(uint8_t channel,
                                                   uint16_t duration_ms);

/*
 The factory EUI-64 (otPlatRadioGetIeeeEui64), written to the 8-byte `out`
 in little-endian byte order.
 */
extern void ziggurat_platform_hw_eui64(uint8_t *out);

/*
 Reboot the MCU. Must not return.
 */
extern void ziggurat_platform_hard_reset(void);

/*
 Fatal error: `msg` is the panic message (not NUL-terminated). Must record
 the message and reset; on EFR32 this routes through the OpenThread crash
 handler's assert machinery so the reset classifies as a crash. Must not
 return.
 */
extern void ziggurat_platform_panic(const uint8_t *msg,
                                    size_t len);

/*
 Post-mortem: describe the previous reset if it was abnormal (a panic,
 assert, or fault dump), writing up to `cap` UTF-8 bytes into `buf` and
 returning the length. Zero when the previous reset was clean or already
 reported.
 */
extern size_t ziggurat_platform_last_reset(uint8_t *buf,
                                           size_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ZIGGURAT_H_ */
